name: CICD
on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Login to DockerHub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker Image
      run: docker build -t  VaibhavYadavAntino/LeadNuturingBackend .
    - name: Publish Image to dockerhub 
      run: docker push VaibhavYadavAntino/LeadNuturingBackend:latest 

  deploy:
    needs: build
    runs-on: [ip-10-0-5-103]
    steps:
    - name: Pull image from Docker Hub
      run: docker pull VaibhavYadavAntino/LeadNuturingBackend:latest

    - name: Delete old container
      run: docker rm -f LeadNuturingBackend-container || true

    - name: Write .env file to EC2
      run: echo "${{ secrets.ENV_FILE }}" > /home/ec2-user/LeadNuturingBackend/.env

    - name: Run Docker container with env
      run: |
        docker run -d -p 5000:5000 \
          --env-file /home/ec2-user/LeadNuturingBackend/.env \
          --name LeadNuturingBackend-container \
          VaibhavYadavAntino/LeadNuturingBackend:latest
